automation to rely upon JS rather than shell
Signed-off-by: Himani1519 <paripathak80@gmail.com>

diff --git a/.github/workflows/build_test.yml b/.github/workflows/build_test.yml
--- a/.github/workflows/build_test.yml
+++ b/.github/workflows/build_test.yml
@@ -56,80 +56,40 @@ jobs:
             echo "ERROR: CHANGELOG.md has not been updated."
             echo "::set-output name=check_commit::false"
           fi
-
       - name: Compare PR description with template
         if: steps.check-changelog.outputs.check_commit == 'false'
+        env:
+          PR_DESCRIPTION: ${{ github.event.pull_request.body }}
         run: |
-         PR_DESCRIPTION="${{ github.event.pull_request.body }}"
-         echo "$PR_DESCRIPTION" > /tmp/pr_description.txt
-         echo "PR DESCRIPTION saved to /tmp/pr_description.txt."
-         cat /tmp/pr_description.txt
-
-         # Save the template content to a file
-         TEMPLATE_CONTENT=$(sed 's/"//g' .github/pull_request_template.md)
-         echo "$TEMPLATE_CONTENT" > /tmp/template_content.txt
-         echo "Template content saved to /tmp/template_content.txt."
-         cat /tmp/template_content.txt
-
-         # Use diff to compare the two files
-         if diff -wB /tmp/pr_description.txt /tmp/template_content.txt > /dev/null; then
-           echo "ERROR: PR description is identical to the template."
-           exit 1
-         else
-           echo "PR description and template are different."
-         fi
-
-      - name: Extract changelog info
-        if: steps.check-changelog.outputs.check_commit == 'false'
-        id: extract-changelog
-        run: |
-          PR_DESCRIPTION=$(cat /tmp/pr_description.txt)
-          # Check if "changelog:" exists in PR description
-          if echo "$PR_DESCRIPTION" | grep -q "VERSION:" && echo "$PR_DESCRIPTION" | grep -q "CHANGELOG:"; then
-            # Extract content after "changelog:"
-            CHANGELOG_TEXT=$(echo $PR_DESCRIPTION | sed -n 's/.*CHANGELOG: \(.*\)/\1/p')
-
-            # Check if extracted CHANGELOG_TEXT is empty or identical to the template content
-            TEMPLATE_CONTENT=$(cat /tmp/template_content.txt)
-            if [ -z "$CHANGELOG_TEXT" ] || [ "$CHANGELOG_TEXT" == "$TEMPLATE_CONTENT" ]; then
-              echo "The changelog information after 'CHANGELOG:' cannot be empty or identical to pull_request_template.md."
-              exit 1
-            fi
-
-            # Extract VERSION: from PR description
-            VERSION=$(echo "$PR_DESCRIPTION" | grep -oP 'VERSION:\s*\K\d+\.\d+\.\d+')
-            echo "Extracted changelog: $CHANGELOG_TEXT"
-            echo "::set-output name=changelog::$CHANGELOG_TEXT"
-            echo "::set-output name=version::$VERSION"
-          else
-            echo -e "No changelog and version information found in PR description. Please add them.\nExpected Format:\nVERSION:vX.XX.X\nCHANGELOG:This is changelog note.\nTo re-run the action, just make a push or commit after updating the PR description or updating the changelog via a manual file changing commit."
+          # Safely print the PR description using Node.js
+          
+          node -e "const fs=require('fs'); fs.writeFileSync('/tmp/pr_description.txt', process.env.PR_DESCRIPTION);"
+          # Use diff to compare the two files
+          if diff -wB /tmp/pr_description.txt .github/pull_request_template.md > /dev/null; then
+            echo "ERROR: PR description is identical to the template."
             exit 1
+          else
+            echo "PR description and template are different."
           fi
 
       - name: Check PR body against changelog
         if: steps.check-changelog.outputs.check_commit == 'false'
+        id: extract-changelog
         run: |
-          ESCAPED_CHANGELOG="${{ steps.extract-changelog.outputs.changelog }}"
-          ESCAPED_CHANGELOG=$(echo "$ESCAPED_CHANGELOG" | sed "s/'/\\\\'/g")
-          VERSION="${{ steps.extract-changelog.outputs.version }}"
-          
-          if ! grep -Fq "$ESCAPED_CHANGELOG" CHANGELOG.md; then
-            # Check if version exists in CHANGELOG.md
-            if grep -q "^## \`$VERSION\`" CHANGELOG.md; then
-              # Append PR description to existing version
-              sed -i "/^## \`$VERSION\`/a - $ESCAPED_CHANGELOG (#${{ github.event.pull_request.number }})" CHANGELOG.md
-            else
-              # Append new version and PR description
-              ANCHOR_LINE=$(awk '/# Basic TN3270 Display Emulator Changelog/ {print NR}' CHANGELOG.md)
-              sed -i "$ANCHOR_LINE a\\
-              \n##  \`$VERSION\`\n- $ESCAPED_CHANGELOG (#${{ github.event.pull_request.number }})\n" CHANGELOG.md
-            fi
+          result=$(node .github/workflows/set-changelog.js ${{ github.event.pull_request.number }})
+          if [ "$result" = "Success" ]; then
             git config --global user.email "zowe-robot@users.noreply.github.com"
             git config --global user.name "Zowe Robot"
             git add CHANGELOG.md
             git commit -s -m "Update changelog with PR #${{ github.event.pull_request.number }} description"
             git push
+            echo "Updated CHANGELOG from description"
+          else
+            echo $result
+            echo -e "No changelog and version information found in PR description. Please add them.\nExpected Format:\nVERSION:X.XX.X\nCHANGELOG:This is changelog note.\nTo re-run the action, just make a push or commit after updating the PR description or updating the changelog via a manual file changing commit."
+            exit 1
           fi
+
       - name: check for changes
         id: check-change
         run: |
@@ -138,7 +98,7 @@ jobs:
             echo "::set-output name=change_detected::false"
           else
             echo "::set-output name=change_detected::true"
-          fi
+            fi
 
   check_changelog:
     if: github.event_name == 'pull_request'
@@ -155,7 +115,8 @@ jobs:
             exit 1
           else
             echo "changelog was updated successfully."
-          fi    
+          fi
+
 
   build:
     runs-on: ubuntu-latest
